# fpl_event_config.yaml file

bucket_name: "leverageai-sandbox-data"
source_name: "fpl_api_event"
source_url: "https://fantasy.premierleague.com/api/event/{event_id}/live"
source_parameters: {"event_ids":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38]}
source_api_version: ""
schema: {}
output_folder_name: "raw"